### ISSUE TITLE
StateMachine: Remove pending transfer timeout≠0 constraint

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#253]
## Background

In the context of a switch, TigerBeetle may need to coordinate with multiple other ledgers. To avoid undermining guarantees given to other ledgers, we should not require pending transfers to time out.

As a bonus, this means I don't have to worry about whether "timeout" is supposed to be "time_out" when used as a verb in the error code.

## Tasks

- [ ] Allow pending transfers to set `timeout = 0`.
- [ ] Remove `pending_transfer_must_timeout`.
- [ ] Update tests accordingly.
- [ ] Update documentation in `transfers.md` (the `timeout` field constraint), `create_transfers.md` (the error code).
- [ ] Update client implementations.

**Comment by jorangreef** [comment]
Thanks @dtornow!

**Comment by jorangreef** [comment]
Re: documentation:

1. When within the switch, the timeout must be set, since the switch is coordinating whether the transaction proceeds or rolls back, and since the payer/payee may be unreliable.

2. When TB is used by payer/payee, then timeout must not be set. Since payer/payee do not coordinate the transaction, only the switch does. Payer/payee must not undermine their promise made to the switch to reserve the balance.

**Comment by matklad** [comment]
Qs:

> Update tests accordingly.

Where do I find relevant tests?

> switch payer/payee

It seems like this talks about some specific scenario of usage. Anything I can read on to better understand the context?

**Comment by sentientwaffle** [comment]
In `state_machine.zig` — I would base off of https://github.com/tigerbeetledb/tigerbeetle/pull/249 (`dj-state-machine-test-table`), because I completely refactored those tests.

The context is a [discussion](https://youtu.be/ZW_emZ4683A?t=2259) between Joran & Dominik Tornow, but it hasn't been written up in more detail yet. The key idea is that if you have multiple independent TigerBeetle clusters (perhaps operated by different entities) they may need to coordinate via two-phase commit protocol to synchronize operations. (For example, a logical payment may consist of physical transfers on several clusters).
