### ISSUE TITLE
StateMachine: Split amounts/accounts in storage

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#255]
## Background

Most of an `Account` is immutable, but the balance fields (`{debits,credits}_{pending,posted}`) are mutable. Currently the whole `Account` object (including balance fields) is stored together in the Accounts object tree. This means that every time a transfer updates an account's balance, the whole account object must be rewritten (and eventually recompacted).

Compaction of immutable data is more amenable to optimizations which reduce write-amplification (e.g. the move-table optimization). This restructure isolates the mutable data to its own groove, minimizing unnecessary rewriting due to compaction.

## Tasks

- [ ] Create a new `AccountBalances` groove.
  - [ ] The groove's key should be `account.timestamp`.
  - [ ] Insert balances to the groove on create account/transfer.
  - [ ] Remove balances from the groove on rollback.
  - [ ] Secondary indexes on each balance field. But no `IdTree`, since it would be identical to the `AccountsGroove`'s `IdTree`. (This will require modifications to `Groove`).
- [ ] Update the "Accounts" groove.
  - [ ] Instead of storing `Account` objects, store "accounts without balances".
  - [ ] The state machine should stitch the "accounts without balances" together with the current `AccountBalances` to get back an `Account`.
- [ ] Add configuration for the new groove to `StateMachine.forest_options`.
