### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#259]
The tasks listed are not guaranteed, and they are not ordered.
The intent is to give a sense of the project's direction.

- :red_circle:: Must be done for the production release.
- :yellow_circle:: Nice-to-have for the production release.

### Stability: Storage

- [x] VSR: Manifest free-set. :red_circle:
- [x] VSR: 256-byte headers. :red_circle:
  - [x] VSR: State machine version in headers. :red_circle:
- [x] VSR: Async checkpoints :red_circle:
- [x] LSM: Remove filter blocks. :red_circle:
- [x] LSM: Re-implement secondary index tombstone optimization. :yellow_circle: [#1352](https://github.com/tigerbeetle/tigerbeetle/pull/1352)
- [ ] [LSM: Compaction optimizations](https://github.com/tigerbeetledb/tigerbeetle/issues/274)
  - [ ] Coalesce small adjacent tables (context: https://github.com/tigerbeetledb/tigerbeetle/pull/463) :red_circle:
  - [ ] "Move-data-block" (more granular than "move table")
  - [ ] Start the next round of compaction reads _before_ starting the merge (cpu) work.
  - [ ] Last-level of each tree should have double-size tables, but half as many. :red_circle:
- [x] VSR: Size manifest trailer, and pace manifest compaction, to guarantee capacity. :red_circle:
- [ ] ~VSR: Encode configuration data into superblock.~ :red_circle:
- [x] VSR: Reserve more space in `SuperBlock.VSRState` for future use. :red_circle:
- [ ] Guard against running a binary against a data file that was created with a different configuration. :yellow_circle:
- [x] LSM: Add value count to `TableInfo`. (And possibly value-block count, since compression will decouple the ratio between the two.) :red_circle:
- [x] Redo snapshots. :red_circle: 
  - [ ] Snapshots should be relative to the op that "creates" them, not the op that compacts them.
  - [ ] Maybe use timestamps instead of ops as snapshot ids.
  - [ ] Store snapshot in manifest block header (like we do for all other blocks).
- [ ] Reserve a some extra space in the superblock for future use, just in case? (Since "growing" the superblock is not possible once a replica is formatted.)
- [x] VSR: Align grid zone start to grid block size. :red_circle:
- [x] VSR: Remove superblock trailers. :red_circle:
  - [x] Encode the client sessions trailer into the grid.
  - [x] Encode the manifest trailer into grid blocks. (As an on-disk doubly-linked list.)
  - [x] Encode the manifest-freeset into one grid block.
  - [ ] Increase the number of superblock copies, since they will be so much smaller.
- [x] VSR: Panic on nondeterminism, don't try to state sync recover. :red_circle: 

### Stability: API

- [x] Client: Add automatic batching to client implementations. (https://github.com/tigerbeetle/tigerbeetle/issues/489, https://github.com/tigerbeetle/tigerbeetle/pull/523) :yellow_circle:
- [x] Client: Handle evictions gracefully (e.g. throw error, allow reconnect – don't panic!) :yellow_circle:
- [x] StateMachine: Maximum linked chain size, to limit `scope_rollback_log` size. (Maybe? :red_circle:)
- [x] StateMachine: `get_account_transfers` (temporary feature until full query API is done). (Requires range queries). :red_circle:
- [x] [StateMachine: Store point-in-time balances](https://github.com/tigerbeetledb/tigerbeetle/issues/357)
  - (Maybe this is no longer in the roadmap due to https://github.com/tigerbeetle/tigerbeetle/pull/1157 un-splitting the Account grooves?)
- [x] [StateMachine: Pending transfer timeouts](https://github.com/tigerbeetle/tigerbeetle/issues/315) (requires range queries) :red_circle:
- [x] [StateMachine: Close account](https://github.com/tigerbeetledb/tigerbeetle/issues/294) (maybe done by https://github.com/tigerbeetle/tigerbeetle/pull/449?)
- [x] StateMachine: Add bulk-import path for data (including timestamps). (Probably need a CLI for this too.) :yellow_circle:
- [ ] StateMachine: Query API (requires range transfers) :yellow_circle:
- [ ] Clients: Expose `flags` as struct-of-boolean instead of integer bitset. (Golang client does this already, Node client does not.) :yellow_circle:
- [ ] Persistent snapshots + historical queries (e.g. "what was the balance of account A at time T").
- [ ] [Bitemporal data](https://github.com/tigerbeetledb/tigerbeetle/issues/157) (maybe?)

### Safety

- [x] VSR: State sync (to catch up >1WAL). :red_circle:
  - [x] VSR: Include checkpoint identifier in `prepare` messages instead of `prepare_ok` messages. (Requires 256-byte headers.) :red_circle:
  - [x] VSR: Remove state sync [kludge](https://github.com/tigerbeetle/tigerbeetle/blob/ac79c9c692c2b552ee5d520366eb51213c30569c/src/vsr/replica.zig#L4327-L4353). (Requires async checkpoints.) :red_circle:
- [ ] VSR: Grid scrubber, to guard against double-faults. :yellow_circle: (This is mostly done.)
- [ ] VSR: `repair_pipeline_read_callback` recurses when messages are cached in the pipeline. Restructure to avoid stack overflow risk. :yellow_circle:
- [ ] Storage: Audit TODOs in `linux.zig` and `src/storage.zig`. :red_circle:
- [ ] VSR: Write + erase a random amount of sectors during replica formatting, to ensure that if all replicas are each deployed to the same model of SSD, that they are not overexposed to faults that impact the same physical block address on each SSD.
  - Note that this does not need to impact the storage format at all.

### Performance

- [ ] StateMachine: Optimistic state machine execution.
- [ ] [LSM: Compaction Beat pacing](https://github.com/tigerbeetle/tigerbeetle/issues/269) :yellow_circle:
  - Spread work more evenly between beats (to avoid latency spikes at the end of a half-bar).
  - LSM storage at the end of each beat will be deterministic (instead of at the end of each half-bar).
- [ ] [LSM: Compaction optimizations](https://github.com/tigerbeetledb/tigerbeetle/issues/274)
  - [ ] LSM: Fix sequential grid-read bottleneck.
- [ ] LSM: Manifest log open prefetch.
- [ ] LSM: Add "sequential" bit for constant-time lookup in consecutive-key value block.
- [ ] LSM: Compress value blocks.
- [x] VSR: Fix checkpoint latency spike:
  - [x] VSR: Allow queuing requests during checkpoint. (See: https://github.com/tigerbeetle/tigerbeetle/issues/558)
  - [x] VSR: Async checkpoints. :red_circle:
- [ ] VSR: Grid block reference-counting or cache/stash, to avoid internal block copying during compaction.
- [ ] VSR: Adaptive message timeouts.
- [ ] VSR: To speed up grid block sync, allow a replica to intelligently send blocks before they are asked for. (This is important for e.g. manifest repair, which is otherwise sequential.) The receiving replica should stash these in its grid block pool so that it can (hopefully) avoid a round trip to repair them.

### Experience: Operations

- [x] LSM: Runtime-configurable NodePool size. :red_circle: (https://github.com/tigerbeetle/tigerbeetle/pull/1447)
- [ ] LSM: Default NodePool size (`lsm_forest_node_count`). (Currently it is constant and too small.) :red_circle:
- [ ] LSM: Replica must panic "nicely" (i.e. with a log message) if `NodePools.acquire()` has no nodes available. :red_circle:
- [ ] LSM: Replica must panic nicely if Grid has insufficient free blocks. :red_circle:
- [ ] LSM: Replica must panic nicely if forest has insufficient tables. (Don't exceed `table_count_max`.) :red_circle:
- [ ] VSR: Reconfiguration protocol
  - [ ] Add/remove replicas from the cluster.
  - [ ] Coordinate rolling replica version upgrades.
- [ ] VSR: Improve asymmetric partition tolerance.
  - [ ] VSR: Table sync congestion control.
- [ ] DNS addressing/lookups (https://github.com/tigerbeetledb/tigerbeetle/issues/74)
- [ ] Metrics (e.g. Prometheus)
- [ ] Structured logging, to make parsing/indexing/searching easier
- [ ] Support for TLS between clients and replicas
- [ ] Disaster recovery tool/mechanism to repair storage determinism problems. (TBD)
- [ ] Document all CLI arguments.

### Experience: Client

- [x] Detect + fail on client/server version or configuration mismatch. :red_circle:
  - [ ] Also https://github.com/tigerbeetledb/tigerbeetle/issues/316
- [x] Node client should use tb_client.

### Testing

- [x] VOPR(hub) running without errors. :red_circle:
  - [x] https://github.com/tigerbeetle/tigerbeetle/issues/1020, etc :red_circle:
- [ ] VOPR: Test different configurations.
- [ ] VOPR: Test additional storage faults.
- [ ] [VOPR: sometimes run with an unrestricted amount of faults](https://github.com/tigerbeetle/tigerbeetle/issues/696)
- [ ] Create StateMachine-level fuzzer. (Probably using Workload).
- [ ] Explore more workloads for the forest fuzzer.
- [ ] Antithesis. :yellow_circle:
- [ ] Test a "full" LSM, to make sure it properly rejects requests. :yellow_circle:
- [ ] Fuzz different compile-time and run-time configurations.
- [ ] Fuzz all components: <https://github.com/tigerbeetledb/tigerbeetle/issues/189>. (Maybe this is unnecessary? Forest fuzzer is a higher priority.)
- [ ] Explicit code coverage marks. (Maybe reuse structured logging or metrics?)

### Documentation

- [ ] Document security model.

**Comment by jorangreef** [comment]
(Closing, since this was unpinned in August)
