### ISSUE TITLE
StateMachine: Pending transfer timeouts

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#315]
(Requires range queries).

## Tasks

- [ ] StateMachine
  - [ ] Add a derived index on `transfer.timestamp + transfer.timeout`.
  - [ ] On state machine commit:
    - Prefetch _the first N_ transfers which will time out by the end of the batch. (Where `N` is a state machine constant (passed in to `StateMachineType`)). This upper-bound guards against adversarial workloads generating many pending transfers which all expire at the same moment to stall the cluster.
    - As each item in the batch is committed, the state machine's "time" increases. As the time increases, void expired transfers.
- [ ] Document:
  - [ ] Semantics of timeout (i.e. the "at most N per op" behavior") — transfer timeout is not exact, it is as soon as possible after expiry.
  - [ ] Don't allow downstream users of TB to choose arbitrary timeouts.

**Comment by batiati** [comment]
Closed by #1657
