### ISSUE TITLE
StateMachine: Store point-in-time balances

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#357]
## Background

Depends on https://github.com/tigerbeetledb/tigerbeetle/issues/255

Goal: Support balance-at-point-in-time queries.
(Implementing querying is not in scope for this issue).

By using an account flag to enable the "account history", the user only has to pay the performance cost when they need the feature.

## Tasks

- [ ] Add a new `Account` flag: `historical_balances` (or another name?).
- [ ] When `Account.flags.historical_balances` is set:
  - Creating the account should also create a 0/0/0/0 entry in `AccountBalancesHistory`.
  - Any transfer which debits or credits the account creates an entry in `AccountBalancesHistory`.
- [ ] Create a new `AccountBalancesHistory` groove.
  - We will be use this for point-in-"time" balance lookups (unlimited snapshots!) by scanning backwards from the queried timestamp.
  - [ ] The groove's key should be `(account.timestamp, transfer.timestamp)`.
  - [ ] The groove's object should be `{debits_pending: u64, debits_posted: u64, credits_pending: u64, credits_posted: u64}`.
  - [ ] Insert balances in the groove on create account/transfer.
  - [ ] Remove balances from the groove on rollback.
  - [ ] No secondary indexes. (Not even an `IdTree`).
- [ ] Add configuration for the new groove to `StateMachine.forest_options`.

## Naming

- Alternative flag names (instead of `history`)?
- Should `AccountBalancesHistory` be `AccountAmountHistory` instead? Since "balance" is the computed (`debits - credits` or `credits - debits`), but we store all 4 amounts.

**Comment by batiati** [comment]
Closed by #1526 and #1733
