### ISSUE TITLE
Docs roadmap for June release

### ISSUE THREAD

**Issue by eatonphil** [tigerbeetle/tigerbeetle#483]
Docs roadmap for a June release. The list is subject to change.

* Client libraries
  * Reference docs
    * Generated automatically and compiles in CI
      * [x] Node
      * [x] Go
      * [x] Java
      * [x] C#
    * [x] Runs in CI
    * Client **build steps** run in CI
      * [x] Linux
      * [x] Mac
      * [x] Windows
  * Sample programs
    * Basic: Create two accounts and insert transfers between them in one direction
      * [x] Has project docs
      * Exists, compiles and runs in CI
        * [x] Node
        * [x] Go
        * [x] Java
        * [x] C#
    * Error handling
      * [x] Has project docs
      * [x] Exists, compiles and runs in CI
    * Two-phase transfer: Create two accounts and insert a pending transfer that is later posted.
      * Exists, compiles and runs in CI
         * [x] Node
         * [x] Go
         * [x] Java
         * [x] C#
    * Currency exchange: Create five accounts (two for two customers in two currencies, one for the service), create 1 5 transfers representing payment from customer A in currency 1 to customer B in currency 2 with a fee paid to the service.
      * [ ] Exists, compiles and runs in CI
* Tutorials
  * [ ] Building a basic TigerBeetle client in X (adaptation of the Basic sample program)
  * [ ] Two-phase commits in X (adaptation of the Two-phase commit sample program)
  * [ ] Building a currency exchange in X (adaptation of the Currency exchange sample program)
* References docs
  * [x] Each operation links to client library docs for the operation
* Integration
  * [ ] Idempotency
    * If their application crashes/restarts it needs to reuse ids to ensure that it doesn't (e.g.) execute a payment twice.
      * That ^^ often requires coordination with another data store.
      * But that ^^ could end up bottlenecking performance.
    * (We touch on it a little in Data Modeling, but I think it needs to be its own section too.)
* Operations (New section)
  * [ ] How to configure backups
  * [ ] How to handle monitoring (what to monitor?)
  * [ ] How many replicas and where should they be
  * [ ] How to pick a cluster identifier (what is it for?)
  * [ ] How to upgrade
  * [ ] Running in kubernetes
  * [ ] System requirements - The importance of clock sync, latency requirements and bounds too (Updating the existing Hardware doc)
  * [ ] How TB differs from other things you might be used to
  * [ ] How to handle security/ trust boundary
* Architecture
  * [ ] TigerBeetle's replication protocol
  * [ ] TigerBeetle's storage system
  * [ ] TigerBeetle's client communication protocol
  * [ ] How does TigerBeetle fit into my existing stack? (Pull out from FAQ entry, add diagrams)
